# Generated by Django 3.1 on 2020-08-27 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='taguse',
            constraint=models.CheckConstraint(check=models.Q(lower_name__regex='^[a-z][a-z0-9_]*$'), name='lowercase_tag_chars_valid'),
        ),
        migrations.AddConstraint(
            model_name='taguse',
            constraint=models.UniqueConstraint(fields=('lower_name', 'day'), name='unique_tag_name_day'),
        ),
    ]
