# Generated by Django 3.0 on 2020-06-07 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('link', models.URLField(max_length=64)),
                ('seen', models.BooleanField(default=False)),
                ('image', models.URLField(blank=True, default='', max_length=128)),
                ('message', models.CharField(blank=True, max_length=128)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('target_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memes.Comment')),
                ('target_meme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memes.Meme')),
                ('target_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memes.Page')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
