# Generated by Django 3.0 on 2020-06-10 13:54

import django.core.validators
from django.db import migrations, models
import memes.models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitelink',
            name='url',
        ),
        migrations.RemoveField(
            model_name='invitelink',
            name='user',
        ),
        migrations.AddField(
            model_name='invitelink',
            name='uses',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='invitelink',
            name='uuid',
            field=models.CharField(default=memes.models.get_invite_link, max_length=7),
        ),
    ]
